// WhiteCadae : Cloudflare Worker (API + service du site statique)

import {
  currentAnswerId, accessOf, progresOf,
  ECHELON_114,
} from './enigmas57.js';
import { handleEchelon, gameRows } from './echelon-api.js';
import { gameLevel, accessLevel, clockUnlocked } from './echelon.js';
import {RELEASES,retiredSong,gatedTrack,gatedAlbum,visibleSong,canListen,musicAlbums,ensureMusicCatalogue,continuousTrack} from './music-catalogue.js';
import {contentAccess} from './content-access.js';
import {buildOrange} from './orange-access.js';
import {handleRoadmap} from './roadmap.js';
export {BrainstormLive} from './brainstorm-live.js';

const SESSION_COOKIE = 'wc_session';
const SESSION_DAYS = 30;
const PBKDF2_ITERATIONS = 100000;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname.startsWith('/music/')) return avecSecurite(await serveMusic(request, env));
    if (url.pathname.startsWith('/api/')) {
      try {
        const refusal=checkWriteOrigin(request,url);
        return avecSecurite(refusal||await handleApi(request, env, url));
      } catch (err) {
        console.error(err.stack || String(err));
        return avecSecurite(json({ error: 'Erreur interne du serveur.' }, 500));
      }
    }
    // Tout le reste est servi par les assets statiques (mode SPA).
    return avecSecurite(await env.ASSETS.fetch(request));
  },
};

// Workers Assets may return the whole MP3 even for Range requests. Native
// players (especially Safari) need real byte ranges to seek before download ends.
// Continuous album variants carry a generated byte length, so their ranges
// are streamed without buffering a complete album in the Worker.
async function serveMusic(request, env) {
  let path;
  try { path=decodeURIComponent(new URL(request.url).pathname); } catch { return new Response('Fichier introuvable',{status:404}); }
  const release=RELEASES.find(album=>path.startsWith('/music/'+album.id+'/'));
  const continuous=continuousTrack(path);
  if(!release)return json({error:'Fichier introuvable.'},404);
  const restricted=!!release;
  if(restricted){
    const item=path===release.cover?release.tracks.reduce((a,b)=>a.minLevel<b.minLevel?a:b):continuous||release.tracks.find(track=>track.src===path);
    if(!item)return json({error:'Fichier introuvable.'},404);
    if(!canListen(item,await listeningAccess(request,env)))return json({error:`Ce contenu se découvre à l’échelon ${item.minLevel}.`},403);
  }
  const headers = new Headers(request.headers);
  const range = headers.get('Range');
  headers.delete('Range');
  const response = await env.ASSETS.fetch(new Request(request, { headers }));
  const outputHeaders = new Headers(response.headers);
  if(restricted){outputHeaders.set('Cache-Control','private, no-store');outputHeaders.set('Vary','Cookie');}
  if (!/^audio\//.test(response.headers.get('Content-Type') || '')) {
    if ((response.headers.get('Content-Type') || '').includes('text/html')) return new Response('Fichier introuvable', { status: 404 });
    return new Response(response.body,{status:response.status,headers:outputHeaders});
  }
  outputHeaders.set('Accept-Ranges', 'bytes');
  const full = () => new Response(response.body, { status: response.status, headers: outputHeaders });
  if (!range || request.method !== 'GET' || response.status !== 200) return full();
  const ifRange = request.headers.get('If-Range');
  if (ifRange && ifRange !== response.headers.get('ETag') && ifRange !== response.headers.get('Last-Modified')) return full();
  const match = /^bytes=(\d*)-(\d*)$/.exec(range.trim());
  if (!match || (!match[1] && !match[2])) return full(); // ignore unsupported/malformed ranges
  // ASSETS.fetch can omit Content-Length even though the final edge response
  // includes it. Derive the byte length from the original, unencoded MP3.
  const knownSize=continuous?.bytes||Number(response.headers.get('Content-Length'));
  const bytes=knownSize?null:new Uint8Array(await response.arrayBuffer());
  const size=knownSize||bytes.byteLength;
  const start = match[1] ? Number(match[1]) : Math.max(0, size - Number(match[2]));
  const end = match[1] && match[2] ? Math.min(Number(match[2]), size - 1) : size - 1;
  if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end || start >= size) {
    if(!bytes)await response.body?.cancel();
    return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}`, 'Accept-Ranges': 'bytes' } });
  }
  outputHeaders.set('Content-Range', `bytes ${start}-${end}/${size}`);
  outputHeaders.set('Content-Length', String(end - start + 1));
  if(bytes)return new Response(bytes.subarray(start,end+1),{status:206,headers:outputHeaders});
  const reader=response.body.getReader();let offset=0;
  const sliced=new ReadableStream({
    async pull(controller){
      try{while(true){
        const {value,done}=await reader.read();if(done){controller.close();return;}
        const low=Math.max(0,start-offset),high=Math.min(value.byteLength,end+1-offset);offset+=value.byteLength;
        if(high>low)controller.enqueue(value.subarray(low,high));
        if(offset>end){controller.close();await reader.cancel();return;}
        if(high>low)return;
      }}catch(error){controller.error(error);}
    },cancel(reason){return reader.cancel(reason);}
  });
  return new Response(sliced,{status:206,headers:outputHeaders});
}

/* ------------------------------------------------- en-têtes de sécurité ---

   Le vrai verrou est `script-src 'self'` : le site n'exécute que ses propres
   fichiers. Si une chaîne écrite par un membre parvenait un jour à s'échapper
   de l'échappement du client, le navigateur refuserait quand même de la
   lancer. Il n'y a aucun script en ligne dans le site : c'est pourquoi le
   repli d'avatar, qui vivait dans un attribut `onerror`, a été déplacé dans
   app.js.

   Les styles gardent 'unsafe-inline' : trois barres de progression posent leur
   largeur en attribut. C'est sans danger comparé aux scripts.

   Les anciennes intégrations externes sont fermées. `frame-src 'none'`
   interdit les cadres intégrés ; `frame-ancestors 'none'` empêche un autre
   site d'encadrer celui-ci pour détourner les clics d'un membre.            */
const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "media-src 'self'",
  "font-src 'self'",
  "connect-src 'self'",
  "worker-src 'self'",
  "manifest-src 'self'",
  "frame-src 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
].join('; ');

const SECURITE = {
  'Content-Security-Policy': CSP,
  // sans quoi un fichier déposé par un membre pourrait être deviné exécutable
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  // Les fonctions vocales retirées n'ont plus besoin d'accès au micro.
  'Permissions-Policy': 'geolocation=(), microphone=(), camera=(), payment=(), usb=()',
  // le navigateur garde le site en HTTPS pendant deux ans, sous-domaines compris
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
};

function avecSecurite(reponse) {
  if(reponse.status===101)return reponse; // Preserve the accepted WebSocket.
  // 204 et 304 n'ont pas de corps : le recopier ferait échouer la construction.
  const sansCorps = [101, 204, 205, 304].includes(reponse.status);
  const sortie = new Response(sansCorps ? null : reponse.body, reponse);
  for (const [nom, valeur] of Object.entries(SECURITE)) sortie.headers.set(nom, valeur);
  return sortie;
}

/* ---------------------------------------------------------------- routing */

function checkWriteOrigin(request,url){
  if(['GET','HEAD','OPTIONS'].includes(request.method))return null;
  const origin=request.headers.get('Origin'),site=request.headers.get('Sec-Fetch-Site');
  if((origin&&origin!==url.origin)||site==='cross-site')return json({error:'Origine de requête non autorisée.'},403);
  if(request.body&&/^\/api\/(signes|echelon|57\/guess|register|login|logout|account|admin)(?:\/|$)/.test(url.pathname)&&!/^application\/json(?:\s*;|$)/i.test(request.headers.get('Content-Type')||''))return json({error:'Une requête JSON est requise.'},415);
  return null;
}

async function handleApi(request, env, url) {
  const path = url.pathname.replace(/\/+$/, '') || '/api';
  const method = request.method;
  const route = (m, pattern) => {
    if (m !== method) return null;
    const re = new RegExp('^' + pattern.replace(/:(\w+)/g, '([^/]+)') + '$');
    const match = path.match(re);
    return match ? match.slice(1).map(decodeURIComponent) : null;
  };

  let p;
  if(path==='/api/roadmap'||path.startsWith('/api/roadmap/'))return handleRoadmap(request,env,url,{getUser,json});
  if(path==='/api/signes'||path.startsWith('/api/signes/'))return handleEchelon(request,env,path.replace(/^\/api\/signes/,'/api/echelon'),{getUser,json});

  // Retired spaces remain stored, but no client can read, write or join them.
  if (/^\/api\/(conversation|community|videographies|videographie|vg-media|vg-comments|arbres|branches|vocal|voix)(?:\/|$)/.test(path)) {
    return json({error:'Cet espace a été retiré. Le parcours se poursuit dans les musiques et les échelons.'},410);
  }

  if (route('GET', '/api/orange')) {
    const user = await getUser(request, env);
    return json(buildOrange(await gameRows(env, user?.id), user));
  }

  if (/^\/api\/(carre|societes|brainstorms|114)(?:\/|$)/.test(path)) {
    return json({error:'Cet espace a été supprimé.'}, 410);
  }

  if (path === '/api/echelon' || path.startsWith('/api/echelon/') ||
      path === '/api/57' || path === '/api/57/guess') {
    return handleEchelon(request, env, path, { getUser, json });
  }

  // Lyrics are read-only; individual song access is checked below.
  if (['POST', 'PUT', 'PATCH'].includes(request.method) &&
      /^\/api\/(annotations|references|passage-references|connections|essays)(?:\/|$)/.test(path)) {
    return json({ error: 'Les paroles sont désormais en lecture seule.' }, 410);
  }
  if (route('GET', '/api/albums')) return listAlbums(env, request);
  if (route('GET', '/api/music')) return json({albums:musicAlbums(await listeningAccess(request,env))});
  if (path==='/api/aa'||path==='/api/journey') return json({error:'Cette page a été retirée.'},410);
  if ((p = route('GET', '/api/songs/:slug'))) return getSong(env, request, p[0]);

  // --- auth
  if (route('POST', '/api/register')) return register(request, env);
  if (route('POST', '/api/login')) return login(request, env);
  if (route('POST', '/api/logout')) return logout(request, env);
  if (route('GET', '/api/me')) return me(request, env);

  // Member photos use the same visibility checks as the roadmap.
  if (route('GET', '/api/users/:username/avatar')) return json({error:'Cette adresse a été retirée.'},410);

  // Profiles have been retired; existing accounts keep their game progress.
  if (/^\/api\/users\/[^/]+$/.test(path)) return json({error:'La page profil a été retirée.'},410);

  // The retired reset must not erase historical access rights.
  if (route('DELETE', '/api/57/progress')) return json({ error: 'Cette ancienne fonction a été retirée.' }, 410);

  // --- le compte : toujours accessible, sinon on ne pourrait plus en sortir
  if (route('PUT', '/api/account/username')) return updateUsername(request, env);
  if (route('PUT', '/api/account/password')) return updatePassword(request, env);
  if (route('POST', '/api/account/avatar')) return updateAvatar(request, env);

  // --- les pièces hautes : chacune exige son échelon, vérifié dans son
  //     gestionnaire (le corps de la requête et l'échelon du visiteur s'y
  //     lisent ensemble). L'ordre n'a pas d'importance : rien ici n'est
  //     couvert par le barrage plus bas.
  // --- le tronc commun : les interprétations. Ouvert dès l'échelon 1, donc à
  //     tout le monde, visiteur compris : le barrage ne ferme plus que ce qui
  //     est au-dessus. On le garde en place : si un jour un échelon doit se
  //     refermer, il suffit de relever la constante.
  if (path.startsWith('/api/') && !path.startsWith('/api/admin/')) {
    const refus = await requireAccess(request, env, 'interpretations');
    if (refus) return refus;
  }

  // Legacy corpus reader remains available for private historical references.
  if (route('GET', '/api/corpus')) return getCorpus(env, request);

  // --- contributions (connecté)
  if ((p = route('DELETE', '/api/annotations/:id'))) return deleteAnnotation(request, env, +p[0]);
  if ((p = route('DELETE', '/api/references/:id'))) return deleteReference(request, env, +p[0]);
  if ((p = route('DELETE', '/api/passage-references/:id'))) return deletePassageReference(request, env, +p[0]);
  if ((p = route('DELETE', '/api/connections/:id'))) return deleteConnection(request, env, +p[0]);
  if ((p = route('DELETE', '/api/essays/:id'))) return deleteEssay(request, env, +p[0]);

  // --- administration
  if (route('POST', '/api/admin/albums')) return adminCreateAlbum(request, env);
  if ((p = route('PUT', '/api/admin/albums/:id'))) return adminUpdateAlbum(request, env, +p[0]);
  if ((p = route('DELETE', '/api/admin/albums/:id'))) return adminDeleteAlbum(request, env, +p[0]);
  if (route('POST', '/api/admin/songs')) return adminCreateSong(request, env);
  if ((p = route('PUT', '/api/admin/songs/:id'))) return adminUpdateSong(request, env, +p[0]);
  if ((p = route('DELETE', '/api/admin/songs/:id'))) return adminDeleteSong(request, env, +p[0]);
  if ((p = route('PUT', '/api/admin/songs/:id/lyrics'))) return adminSetLyrics(request, env, +p[0]);
  if ((p = route('PUT', '/api/admin/songs/:id/duration'))) return adminSetDuration(request, env, +p[0]);

  return json({ error: 'Route introuvable.' }, 404);
}

/* ---------------------------------------------------------------- helpers */

// `no-store` : toutes ces réponses dépendent de qui les demande, la session,
// l'échelon atteint, les brouillons qu'on est seul à voir. Aucune ne doit
// dormir dans un cache intermédiaire, encore moins être resservie à
// quelqu'un d'autre. (L'avatar, lui, forge sa propre réponse et reste
// cachable : c'est une image publique.)
function json(data, status = 200, headers = {}) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'no-store',
      ...headers,
    },
  });
}

async function readJson(request) {
  try {
    if(!request.body)return null;
    const reader=request.body.getReader(),chunks=[];let size=0;
    for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>2_000_000){await reader.cancel();return null;}chunks.push(value);}
    const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}
    return JSON.parse(new TextDecoder().decode(bytes));
  } catch {
    return null;
  }
}

function toHex(buf) {
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function fromHex(hex) {
  return new Uint8Array(hex.match(/.{2}/g).map((b) => parseInt(b, 16)));
}

async function pbkdf2(password, salt) {
  const key = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']
  );
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: PBKDF2_ITERATIONS, hash: 'SHA-256' },
    key, 256
  );
  return toHex(bits);
}

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const hash = await pbkdf2(password, salt);
  return `${toHex(salt)}:${hash}`;
}

async function verifyPassword(password, stored) {
  const [saltHex, expected] = stored.split(':');
  const actual = await pbkdf2(password, fromHex(saltHex));
  if (actual.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < actual.length; i++) diff |= actual.charCodeAt(i) ^ expected.charCodeAt(i);
  return diff === 0;
}

function newToken() {
  return toHex(crypto.getRandomValues(new Uint8Array(32)));
}

function fromBase64(b64) {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

function getCookie(request, name) {
  const cookies = request.headers.get('Cookie') || '';
  const match = cookies.match(new RegExp('(?:^|;\\s*)' + name + '=([^;]+)'));
  return match ? match[1] : null;
}

function sessionCookie(token, maxAgeSeconds) {
  return `${SESSION_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAgeSeconds}`;
}

async function getUser(request, env) {
  const token = getCookie(request, SESSION_COOKIE);
  if (!token) return null;
  const row = await env.DB.prepare(
    `SELECT u.id, u.email, u.username, u.is_admin
       FROM sessions s JOIN users u ON u.id = s.user_id
      WHERE s.token = ?1 AND s.expires_at > datetime('now')`
  ).bind(token).first();
  return row || null;
}

async function listeningAccess(request,env) {
  const user=await getUser(request,env);
  return contentAccess(user,user?await gameRows(env,user.id):[]);
}

async function requireUser(request, env) {
  const user = await getUser(request, env);
  if (!user) throw json({ error: 'Connexion requise.' }, 401);
  return user;
}

async function requireAdmin(request, env) {
  const user = await requireUser(request, env);
  if (!user.is_admin) throw json({ error: 'Réservé à l’administrateur.' }, 403);
  return user;
}

/* --------------------------------------------------- ce que l'échelon ouvre

   Le 57 commande le reste du site : sans mot de passe trouvé, il n'y a que
   lui. Les pages s'ouvrent ensuite une à une (voir accessOf). Le barrage vit
   dans le code : masquer un lien dans l'interface ne ferme aucune porte.

   L'artiste en est exempté : il ne peut pas se retrouver enfermé dehors de
   son propre site par un jeu dont il connaît déjà les réponses.            */

function activeAccess(echelon) {
  return {...accessOf(echelon), penseMieux:false, carre:false, brainstorm:false, cent14:false, conversation:false, topics:false, videographie:false};
}

async function viewerAccess(request, env) {
  const user = await getUser(request, env);
  // Sans compte on est au sol, comme tout le monde : l'échelon 1 ouvre déjà
  // les interprétations, en lecture.
  if (!user) return { user: null, echelon: 1, solved: new Set(), access: activeAccess(1) };
  if (user.is_admin) {
    return { user, echelon: Infinity, solved: new Set(), access: activeAccess(Infinity) };
  }
  const rows = await riddleRows(env, user.id);
  const { solved } = progresOf(rows.filter((r) => r.solved_at).map((r) => r.riddle_id));
  const echelon = accessLevel(rows);
  const spaces=contentAccess(user,rows);
  return { user, echelon, solved, access: {...activeAccess(echelon), conversation:spaces.conversation,videographie:spaces.videographie} };
}

// L'échelon exigé par une pièce, et un refus prêt à servir. Le message ne dit
// jamais ce qu'il faudrait trouver.
async function requireEchelon(request, env, minimum, cle) {
  const vu = await viewerAccess(request, env);
  if (vu.echelon >= minimum) return { vu, refus: null };
  return { vu, refus: json({ error: 'Ce n’est pas encore ouvert.', locked: cle }, 403) };
}

// Renvoie null si tout est ouvert, sinon la réponse à servir telle quelle.
// Le message ne dit jamais ce qu'il faudrait trouver.
async function requireAccess(request, env, ...cles) {
  const { access } = await viewerAccess(request, env);
  const manque = cles.find((c) => !access[c]);
  if (!manque) return null;
  return json({ error: 'Ce n’est pas encore ouvert.', locked: manque }, 403);
}

function slugify(text) {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '') || 'sans-titre';
}

async function uniqueSlug(env, table, base) {
  let slug = base;
  for (let i = 2; i < 100; i++) {
    const existing = await env.DB.prepare(`SELECT id FROM ${table} WHERE slug = ?1`).bind(slug).first();
    if (!existing) return slug;
    slug = `${base}-${i}`;
  }
  throw new Error('Impossible de générer un slug unique.');
}

function countWords(text) {
  const t = text.trim();
  return t ? t.split(/\s+/).length : 0;
}

// Les colonnes artist/note (migration 0010) sont ajoutées à la volée si la
// migration n'a pas encore été appliquée : ALTER TABLE n'est pas idempotent
// en SQLite, on regarde donc d'abord ce qui existe.
let refColumnsReady = false;
async function ensureReferenceColumns(env) {
  if (refColumnsReady) return;
  const { results } = await env.DB.prepare('PRAGMA table_info(annotation_references)').all();
  const have = new Set((results || []).map((c) => c.name));
  for (const col of ['artist', 'note']) {
    if (!have.has(col)) {
      await env.DB.prepare(`ALTER TABLE annotation_references ADD COLUMN ${col} TEXT`).run();
    }
  }
  refColumnsReady = true;
}

// Valide la liste de références d'une interprétation. Une référence libre
// nomme l'œuvre et son artiste ; une référence interne vise un passage d'un
// morceau (ref_line_id..ref_end_line_id). Les deux portent une explication.
// Retourne un tableau normalisé, ou une Response d'erreur.
async function parseReferences(env, raw) {
  if (raw == null) return [];
  if (!Array.isArray(raw)) return json({ error: 'Références invalides.' }, 400);
  if (raw.length > 10) return json({ error: '10 références maximum par interprétation.' }, 400);
  const refs = [];
  for (const r of raw) {
    if (r && r.ref_line_id != null) {
      // référence interne vers un passage d'un morceau
      const startId = Number(r.ref_line_id);
      const endId = r.ref_end_line_id == null ? startId : Number(r.ref_end_line_id);
      const start = await env.DB.prepare(
        'SELECT l.id, l.text, l.line_number, l.song_id, s.title FROM lyric_lines l JOIN songs s ON s.id = l.song_id WHERE l.id = ?1'
      ).bind(startId).first();
      const end = startId === endId ? start : await env.DB.prepare(
        'SELECT id, text, line_number, song_id FROM lyric_lines WHERE id = ?1'
      ).bind(endId).first();
      if (!start || !end) return json({ error: 'Passage référencé introuvable.' }, 400);
      if (start.song_id !== end.song_id) return json({ error: 'Le passage référencé doit rester dans un même morceau.' }, 400);
      if (end.line_number < start.line_number) return json({ error: 'Passage référencé invalide (fin avant le début).' }, 400);
      const excerpt = start.text.length > 60 ? start.text.slice(0, 57) + '…' : start.text;
      const label = `${start.title} : « ${excerpt}${endId !== startId ? ' […]' : ''} »`;
      const note = String((r && r.note) || '').trim();
      if (note.length > 2000) return json({ error: 'Explication de référence trop longue (2000 caractères max).' }, 400);
      refs.push({
        label, artist: null, note: note || null, url: null,
        ref_song_id: start.song_id, ref_line_id: startId, ref_end_line_id: endId,
      });
      continue;
    }
    const label = String((r && r.label) || '').trim();
    const artist = String((r && r.artist) || '').trim();
    const note = String((r && r.note) || '').trim();
    if (!label) continue;
    if (label.length > 300) return json({ error: 'Nom de l’œuvre trop long (300 caractères max).' }, 400);
    if (artist.length > 300) return json({ error: 'Nom de l’artiste trop long (300 caractères max).' }, 400);
    if (note.length > 2000) return json({ error: 'Explication de référence trop longue (2000 caractères max).' }, 400);
    refs.push({
      label, artist: artist || null, note: note || null, url: null,
      ref_song_id: null, ref_line_id: null, ref_end_line_id: null,
    });
  }
  return refs;
}

async function replaceReferences(env, annotationId, refs) {
  await ensureReferenceColumns(env);
  const statements = [
    env.DB.prepare('DELETE FROM annotation_references WHERE annotation_id = ?1').bind(annotationId),
  ];
  refs.forEach((r, i) => statements.push(refInsert(env, annotationId, i, r)));
  await env.DB.batch(statements);
}

function refInsert(env, annotationId, position, r) {
  return env.DB.prepare(
    `INSERT INTO annotation_references
      (annotation_id, position, label, artist, note, url, ref_song_id, ref_line_id, ref_end_line_id)
     VALUES (?1, ?2, ?3, ?4, ?5, NULL, ?6, ?7, ?8)`
  ).bind(annotationId, position, r.label, r.artist || null, r.note || null,
         r.ref_song_id || null, r.ref_line_id || null, r.ref_end_line_id || null);
}

// Une référence se publie seule, après coup, sur une interprétation qui
// existe déjà : elle lui est greffée sans qu'il faille la réécrire.
async function addReference(request, env, annotationId) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }
  const ann = await env.DB.prepare('SELECT id, user_id FROM annotations WHERE id = ?1').bind(annotationId).first();
  if (!ann) return json({ error: 'Interprétation introuvable.' }, 404);
  if (ann.user_id !== user.id && !user.is_admin) return json({ error: 'Action non autorisée.' }, 403);

  const body = await readJson(request);
  const parsed = await parseReferences(env, [body]);
  if (parsed instanceof Response) return parsed;
  if (!parsed.length) return json({ error: 'Référence vide.' }, 400);

  await ensureReferenceColumns(env);
  const n = (await env.DB.prepare(
    'SELECT COUNT(*) AS n FROM annotation_references WHERE annotation_id = ?1'
  ).bind(annotationId).first()).n;
  if (n >= 10) return json({ error: '10 références maximum par interprétation.' }, 400);
  await refInsert(env, annotationId, n, parsed[0]).run();
  return json({ ok: true });
}

async function deleteReference(request, env, id) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }
  const row = await env.DB.prepare(
    `SELECT r.id, a.user_id FROM annotation_references r
       JOIN annotations a ON a.id = r.annotation_id WHERE r.id = ?1`
  ).bind(id).first();
  if (!row) return json({ error: 'Référence introuvable.' }, 404);
  if (row.user_id !== user.id && !user.is_admin) return json({ error: 'Action non autorisée.' }, 403);
  await env.DB.prepare('DELETE FROM annotation_references WHERE id = ?1').bind(id).run();
  return json({ ok: true });
}

/* ------------------------------------------------------------------- auth */

/* ------------------------------------------------- le barrage des essais ---

   Deux portes s'ouvrent sans rien prouver : la connexion et l'inscription. Sans
   compteur, on peut y taper indéfiniment : essayer des mots de passe de
   membres d'un côté, fabriquer des comptes jetables de l'autre. Or un compte
   jetable, c'est un essai de plus sur les signes du 57 : le minuteur du jeu ne
   tient que par compte, il ne coûte donc rien à qui sait en créer mille.

   Le compteur est tenu par adresse dans une fenêtre fixe à partir du premier
   essai. Il complète le minuteur du jeu et limite la création de comptes en
   masse, sans prétendre empêcher un contournement par plusieurs adresses IP.

   L'adresse vient de `CF-Connecting-IP`, que le réseau de Cloudflare pose
   lui-même : elle ne peut pas être forgée par le visiteur, contrairement à
   `X-Forwarded-For`, qu'on se garde bien de lire. En développement, wrangler
   la pose aussi. Le garde-fou sur son absence n'est donc qu'une ceinture de
   plus : sans adresse, on ne saurait de toute façon pas quoi compter.       */

const barrageTables=new WeakMap();
async function ensureBarrageTable(env){
  if(!barrageTables.has(env.DB)){
    const pending=env.DB.prepare(`CREATE TABLE IF NOT EXISTS auth_attempts (
      cle TEXT PRIMARY KEY,compte INTEGER NOT NULL DEFAULT 0,fenetre TEXT NOT NULL DEFAULT (datetime('now'))
    )`).run().catch(error=>{barrageTables.delete(env.DB);throw error;});
    barrageTables.set(env.DB,pending);
  }
  await barrageTables.get(env.DB);
}
function adresseDe(request){return request.headers.get('CF-Connecting-IP')||null;}
// Atomically reserve an attempt before hashing or writing, including simultaneous requests.
async function barrage(request,env,quoi,max,fenetreSecondes){
  const ip=adresseDe(request);if(!ip)return null;
  await ensureBarrageTable(env);
  const key=`${quoi}:${ip}`;
  const admitted=await env.DB.prepare(`INSERT INTO auth_attempts(cle,compte,fenetre) VALUES(?1,1,datetime('now'))
    ON CONFLICT(cle) DO UPDATE SET
      compte=CASE WHEN (julianday('now')-julianday(fenetre))*86400>=?2 THEN 1 ELSE compte+1 END,
      fenetre=CASE WHEN (julianday('now')-julianday(fenetre))*86400>=?2 THEN datetime('now') ELSE fenetre END
    WHERE compte<?3 OR (julianday('now')-julianday(fenetre))*86400>=?2 RETURNING compte`).bind(key,fenetreSecondes,max).first();
  if(!admitted){
    const row=await env.DB.prepare("SELECT (julianday('now')-julianday(fenetre))*86400 AS age FROM auth_attempts WHERE cle=?1").bind(key).first();
    return json({error:'Trop de tentatives. Réessayez plus tard.'},429,{'Retry-After':String(Math.max(1,Math.ceil(fenetreSecondes-(row?.age||0))))});
  }
  await env.DB.prepare("DELETE FROM auth_attempts WHERE julianday('now')-julianday(fenetre)>1").run();
  return null;
}

// Assez large pour une famille derrière une même adresse, assez étroit pour
// qu'on ne fabrique pas une armée de comptes jetables.
const BARRAGE_CONNEXION = { max: 20, fenetre: 15 * 60 };
const BARRAGE_INSCRIPTION = { max: 6, fenetre: 60 * 60 };

async function register(request, env) {
  const stop = await barrage(request, env, 'inscription', BARRAGE_INSCRIPTION.max, BARRAGE_INSCRIPTION.fenetre);
  if (stop) return stop;

  const body = await readJson(request);
  if (!body) return json({ error: 'Requête invalide.' }, 400);
  const email = String(body.email || '').trim().toLowerCase();
  const username = String(body.username || '').trim();
  const password = String(body.password || '');

  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return json({ error: 'Adresse email invalide.' }, 400);
  if (!/^[\p{L}\p{N} _.-]{3,30}$/u.test(username))
    return json({ error: 'Le pseudo doit faire entre 3 et 30 caractères (lettres, chiffres, espaces, . _ -).' }, 400);
  if (password.length > 1024 || email.length > 254) return json({error:'Identifiants trop longs.'},400);
  if (password.length < 8) return json({ error: 'Le mot de passe doit faire au moins 8 caractères.' }, 400);

  const existing = await env.DB.prepare(
    'SELECT id, email, username FROM users WHERE email = ?1 OR username = ?2 COLLATE NOCASE'
  ).bind(email, username).first();
  if (existing) {
    return json({ error: existing.email === email ? 'Un compte existe déjà avec cet email.' : 'Ce pseudo est déjà pris.' }, 409);
  }

  // An unverified email address cannot confer administrative privileges.
  // Existing administrators keep their role; new roles are provisioned privately.
  const isAdmin = 0;
  const passwordHash = await hashPassword(password);

  const result = await env.DB.prepare(
    'INSERT INTO users (email, username, password_hash, is_admin) SELECT ?1, ?2, ?3, ?4 WHERE NOT EXISTS(SELECT 1 FROM users WHERE email=?1 OR username=?2 COLLATE NOCASE)'
  ).bind(email, username, passwordHash, isAdmin).run();
  if(!result.meta.changes)return json({error:'Cet email ou ce pseudo est déjà utilisé.'},409);

  const userId = result.meta.last_row_id;
  return openSession(env, { id: userId, email, username, is_admin: isAdmin });
}

async function login(request, env) {
  // Count every admitted request so parallel password checks cannot bypass the limit.
  const stop = await barrage(request, env, 'connexion', BARRAGE_CONNEXION.max, BARRAGE_CONNEXION.fenetre);
  if (stop) return stop;

  const body = await readJson(request);
  if (!body) return json({ error: 'Requête invalide.' }, 400);
  const email = String(body.email || '').trim().toLowerCase();
  const password = String(body.password || '');

  if(password.length>1024||email.length>254)return json({error:'Identifiants trop longs.'},400);
  const user = await env.DB.prepare(
    'SELECT id, email, username, password_hash, is_admin FROM users WHERE email = ?1'
  ).bind(email).first();
  if (!user || !(await verifyPassword(password, user.password_hash))) {
    return json({ error: 'Email ou mot de passe incorrect.' }, 401);
  }
  return openSession(env, user);
}

async function openSession(env, user) {
  // Nettoyage opportuniste des sessions expirées.
  await env.DB.prepare(`DELETE FROM sessions WHERE expires_at <= datetime('now')`).run();
  const token = newToken();
  const maxAge = SESSION_DAYS * 24 * 3600;
  await env.DB.prepare(
    `INSERT INTO sessions (token, user_id, expires_at) VALUES (?1, ?2, datetime('now', '+${SESSION_DAYS} days'))`
  ).bind(token, user.id).run();
  return json(
    { user: { id: user.id, email: user.email, username: user.username, is_admin: !!user.is_admin } },
    200,
    { 'Set-Cookie': sessionCookie(token, maxAge) }
  );
}

async function logout(request, env) {
  const token = getCookie(request, SESSION_COOKIE);
  if (token) await env.DB.prepare('DELETE FROM sessions WHERE token = ?1').bind(token).run();
  return json({ ok: true }, 200, { 'Set-Cookie': sessionCookie('', 0) });
}

// La session porte aussi ce que l'échelon ouvre et le minuteur d'essai :
// commun à tous les signes du site. L'interface s'y règle dès le chargement,
// sans attendre l'état du jeu.
async function me(request, env) {
  const { user, access, echelon } = await viewerAccess(request, env);
  const rows=user?await gameRows(env,user.id):[];
  return json({
    user: user ? { ...user, is_admin: !!user.is_admin } : null,
    access:{...access,horloge:clockUnlocked(rows)},
    echelon: Number.isFinite(echelon) ? echelon : ECHELON_114,
    gameEchelon: gameLevel(rows),
    attenteMs: 0,
  });
}

/* ---------------------------------------------------------------- lecture */

// Toutes les phrases de tous les morceaux (hors balises de section et
// lignes vides) : sert au constructeur d'interprétations d'ensemble et
// au moteur de suggestions d'échos.
async function getCorpus(env, request) {
  const viewer = await getUser(request, env);
  const viewerId = viewer ? viewer.id : 0;
  const unlocked=await listeningAccess(request,env);
  const songs = (await env.DB.prepare(
    'SELECT id, title, slug FROM songs ORDER BY title'
  ).all()).results.filter(song=>visibleSong(song,unlocked));
  const visibleIds=new Set(songs.map(song=>song.id));
  const lines = (await env.DB.prepare(
    `SELECT id, song_id, line_number, text FROM lyric_lines
      WHERE text <> '' AND text NOT LIKE '[%' ORDER BY song_id, line_number`
  ).all()).results.filter(line=>visibleIds.has(line.song_id));

  // Nombre de MES interprétations couvrant chaque phrase : une référence
  // interne ne vise qu'un passage que j'ai déjà interprété, puisque je suis
  // le seul à lire ce que j'écris.
  const spans = (await env.DB.prepare(
    `SELECT a.song_id, ls.line_number AS from_no,
            COALESCE(le.line_number, ls.line_number) AS to_no
       FROM annotations a
       JOIN lyric_lines ls ON ls.id = a.line_id
       LEFT JOIN lyric_lines le ON le.id = a.end_line_id
      WHERE a.line_id IS NOT NULL AND a.user_id = ?1`
  ).bind(viewerId).all()).results;

  // tableau de différences par morceau : O(phrases + interprétations)
  const deltas = new Map();
  for (const s of spans) {
    if (!deltas.has(s.song_id)) deltas.set(s.song_id, new Map());
    const d = deltas.get(s.song_id);
    const lo = Math.min(s.from_no, s.to_no);
    const hi = Math.max(s.from_no, s.to_no);
    d.set(lo, (d.get(lo) || 0) + 1);
    d.set(hi + 1, (d.get(hi + 1) || 0) - 1);
  }
  // Les balises de section créent des trous dans la numérotation : on
  // applique tous les deltas jusqu'au numéro de phrase courant.
  let currentSong = null;
  let running = 0;
  let keys = [];
  let dmap = null;
  let ki = 0;
  for (const line of lines) {
    if (line.song_id !== currentSong) {
      currentSong = line.song_id;
      running = 0;
      ki = 0;
      dmap = deltas.get(currentSong) || null;
      keys = dmap ? [...dmap.keys()].sort((a, b) => a - b) : [];
    }
    while (ki < keys.length && keys[ki] <= line.line_number) {
      running += dmap.get(keys[ki]);
      ki++;
    }
    line.interp = running;
  }

  return json({ songs, lines });
}

const cataloguesRenamed = new WeakSet();
async function listAlbums(env, request) {
  await ensureMusicCatalogue(env);
  const unlocked=await listeningAccess(request,env);
  // Apply the targeted, idempotent catalogue migration through the existing
  // database binding; no extra account-wide D1 permission is needed.
  if (!cataloguesRenamed.has(env.DB)) {
    await env.DB.prepare(`UPDATE albums SET title = '114'
      WHERE slug IN ('114','fais-mieux') AND title IN ('114','Fais mieux','Fais Mieux')
        AND EXISTS (SELECT 1 FROM songs WHERE album_id = albums.id AND slug = 'fais-mieux')`).run();
    cataloguesRenamed.add(env.DB);
  }
  const albums = (await env.DB.prepare(
    'SELECT id, title, slug, release_date, is_single FROM albums ORDER BY position, release_date'
  ).all()).results.filter(album=>!gatedAlbum(album.slug)||gatedAlbum(album.slug).tracks.some(track=>canListen(track,unlocked)));
  const songs = (await env.DB.prepare(
    `SELECT s.id, s.album_id, s.title, s.slug, s.track_number,
            (SELECT COUNT(*) FROM lyric_lines l WHERE l.song_id = s.id AND l.text <> '') AS line_count
       FROM songs s ORDER BY s.track_number, s.title`
  ).all()).results.filter(song=>visibleSong(song,unlocked));
  for (const album of albums) {
    album.is_single = !!album.is_single;
    album.songs = songs.filter((s) => s.album_id === album.id);
    const release=gatedAlbum(album.slug);
    if(release){album.title=release.album;album.songs.sort((a,b)=>release.tracks.findIndex(t=>t.slug===a.slug)-release.tracks.findIndex(t=>t.slug===b.slug));album.songs.forEach(song=>{song.track_number=release.tracks.findIndex(t=>t.slug===song.slug)+1;const track=gatedTrack(song.slug);if(track)song.title=track.title;});}
  }
  const orphans = songs.filter((s) => !albums.some((a) => a.id === s.album_id));
  return json({ albums, orphans });
}

async function getSong(env, request, slug) {
  if(retiredSong(slug))return json({error:'Ce morceau a été retiré.'},404);
  const track=gatedTrack(slug);
  if(track){
    if(!canListen(track,await listeningAccess(request,env)))return json({error:`Ces paroles se découvrent à l’échelon ${track.minLevel}.`},403);
  }
  if (slug === 'meta-moi') await ensureMusicCatalogue(env);
  const song = await env.DB.prepare(
    `SELECT s.id, s.title, s.slug, s.track_number, s.youtube_url, s.duration_seconds, s.album_id,
            al.title AS album_title
       FROM songs s LEFT JOIN albums al ON al.id = s.album_id
      WHERE s.slug = ?1`
  ).bind(slug).first();
  if (!song) return json({ error: 'Chanson introuvable.' }, 404);
  if(track){song.title=track.title;song.duration_seconds=track.duration;song.album_title=RELEASES.find(album=>album.tracks.includes(track)).album;}

  const lines = (await env.DB.prepare(
    'SELECT id, line_number, text FROM lyric_lines WHERE song_id = ?1 ORDER BY line_number'
  ).bind(song.id).all()).results;

  return json({ song, lines });
}

/* ------------------------------------------------------------ annotations */

async function createAnnotation(request, env) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const body = await readJson(request);
  if (!body) return json({ error: 'Requête invalide.' }, 400);
  const songId = Number(body.song_id);
  const lineId = body.line_id == null ? null : Number(body.line_id);
  let wordStart = body.word_start == null ? null : Number(body.word_start);
  let wordEnd = body.word_end == null ? wordStart : Number(body.word_end);
  const content = String(body.content || '').trim();

  if (!content) return json({ error: 'L’explication ne peut pas être vide.' }, 400);
  if (content.length > 5000) return json({ error: 'Explication trop longue (5000 caractères max).' }, 400);

  const song = await env.DB.prepare('SELECT id FROM songs WHERE id = ?1').bind(songId).first();
  if (!song) return json({ error: 'Chanson introuvable.' }, 404);

  let targetType;
  let endLineId = body.end_line_id == null ? null : Number(body.end_line_id);
  if (lineId != null && endLineId != null && endLineId !== lineId) {
    // passage multi-phrases : de (line_id, word_start) à (end_line_id, word_end)
    const start = await env.DB.prepare(
      'SELECT id, text, line_number FROM lyric_lines WHERE id = ?1 AND song_id = ?2'
    ).bind(lineId, songId).first();
    const end = await env.DB.prepare(
      'SELECT id, text, line_number FROM lyric_lines WHERE id = ?1 AND song_id = ?2'
    ).bind(endLineId, songId).first();
    if (!start || !end) return json({ error: 'Ligne introuvable.' }, 404);
    if (end.line_number <= start.line_number) return json({ error: 'Passage invalide (fin avant le début).' }, 400);
    if (wordStart == null) wordStart = 0;
    if (body.word_end == null) wordEnd = countWords(end.text) - 1;
    if (
      !Number.isInteger(wordStart) || !Number.isInteger(wordEnd) ||
      wordStart < 0 || wordStart >= countWords(start.text) ||
      wordEnd < 0 || wordEnd >= countWords(end.text)
    ) {
      return json({ error: 'Position de mot invalide.' }, 400);
    }
    targetType = 'passage';
  } else if (lineId != null) {
    endLineId = null;
    const line = await env.DB.prepare(
      'SELECT id, text FROM lyric_lines WHERE id = ?1 AND song_id = ?2'
    ).bind(lineId, songId).first();
    if (!line) return json({ error: 'Ligne introuvable.' }, 404);
    if (wordStart != null) {
      const nWords = countWords(line.text);
      if (
        !Number.isInteger(wordStart) || !Number.isInteger(wordEnd) ||
        wordStart < 0 || wordEnd < wordStart || wordEnd >= nWords
      ) {
        return json({ error: 'Position de mot invalide.' }, 400);
      }
      targetType = 'word';
    } else {
      wordEnd = null;
      targetType = 'line';
    }
  } else {
    wordStart = null;
    wordEnd = null;
    endLineId = null;
    targetType = ['song', 'title', 'duration'].includes(body.target_type) ? body.target_type : 'song';
  }

  const refs = await parseReferences(env, body.references);
  if (refs instanceof Response) return refs;

  // Grille de lecture : le rang de cette lecture parmi celles que cet
  // auteur a déjà écrites sur cette même cible exacte (superposition
  // simultanée de plusieurs lectures possibles d'un même passage).
  const gridNumber = await nextGridNumber(env, user.id, songId, targetType, lineId, wordStart, wordEnd, endLineId);

  // Toute nouvelle interprétation naît en brouillon privé : elle ne devient
  // visible des autres que lorsque son auteur publie une nouvelle version.
  const result = await env.DB.prepare(
    `INSERT INTO annotations (user_id, song_id, target_type, line_id, word_start, word_end, end_line_id, content, is_published, version_id, grid_number)
     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, 0, NULL, ?9)`
  ).bind(user.id, songId, targetType, lineId, wordStart, wordEnd, endLineId, content, gridNumber).run();

  const annotationId = result.meta.last_row_id;
  if (refs.length) await replaceReferences(env, annotationId, refs);

  return json({ id: annotationId }, 201);
}

// Rang (à partir de 1) de la prochaine lecture de cet auteur sur cette cible
// exacte, parmi celles qu'il a déjà écrites : jamais recalculé après coup.
async function nextGridNumber(env, userId, songId, targetType, lineId, wordStart, wordEnd, endLineId) {
  const row = await env.DB.prepare(
    `SELECT COALESCE(MAX(grid_number), 0) AS n FROM annotations
      WHERE user_id = ?1 AND song_id = ?2 AND target_type = ?3
        AND line_id IS ?4 AND word_start IS ?5 AND word_end IS ?6 AND end_line_id IS ?7`
  ).bind(userId, songId, targetType, lineId, wordStart, wordEnd, endLineId).first();
  return row.n + 1;
}

async function updateAnnotation(request, env, id) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const body = await readJson(request);
  const content = String((body && body.content) || '').trim();
  if (!content) return json({ error: 'L’explication ne peut pas être vide.' }, 400);
  if (content.length > 5000) return json({ error: 'Explication trop longue (5000 caractères max).' }, 400);

  const ann = await env.DB.prepare('SELECT id, user_id FROM annotations WHERE id = ?1').bind(id).first();
  if (!ann) return json({ error: 'Annotation introuvable.' }, 404);
  if (ann.user_id !== user.id && !user.is_admin) return json({ error: 'Vous ne pouvez modifier que vos propres explications.' }, 403);

  const refs = await parseReferences(env, body.references);
  if (refs instanceof Response) return refs;

  // Toute modification repasse l'interprétation en brouillon : elle
  // redevient invisible pour les autres jusqu'à la prochaine publication.
  await env.DB.prepare(
    `UPDATE annotations SET content = ?1, updated_at = datetime('now'), is_published = 0, version_id = NULL WHERE id = ?2`
  ).bind(content, id).run();
  if (body.references !== undefined) await replaceReferences(env, id, refs);
  return json({ ok: true });
}

async function deleteAnnotation(request, env, id) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const ann = await env.DB.prepare('SELECT id, user_id FROM annotations WHERE id = ?1').bind(id).first();
  if (!ann) return json({ error: 'Annotation introuvable.' }, 404);
  if (ann.user_id !== user.id && !user.is_admin) return json({ error: 'Vous ne pouvez supprimer que vos propres explications.' }, 403);

  await env.DB.batch([
    env.DB.prepare('DELETE FROM annotations WHERE id = ?1').bind(id),
  ]);
  return json({ ok: true });
}

/* ------------------------------------------------------------- connexions */

async function createConnection(request, env) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const body = await readJson(request);
  if (!body) return json({ error: 'Requête invalide.' }, 400);
  const songA = Number(body.song_a_id);
  const songB = Number(body.song_b_id);
  const explanation = String(body.explanation || '').trim();

  if (!explanation) return json({ error: 'Expliquez en quoi les deux chansons sont reliées.' }, 400);
  if (explanation.length > 5000) return json({ error: 'Explication trop longue (5000 caractères max).' }, 400);
  if (!songA || !songB || songA === songB) return json({ error: 'Choisissez deux chansons différentes.' }, 400);

  const found = (await env.DB.prepare(
    'SELECT id FROM songs WHERE id IN (?1, ?2)'
  ).bind(songA, songB).all()).results;
  if (found.length !== 2) return json({ error: 'Chanson introuvable.' }, 404);

  const result = await env.DB.prepare(
    'INSERT INTO song_connections (song_a_id, song_b_id, user_id, explanation) VALUES (?1, ?2, ?3, ?4)'
  ).bind(songA, songB, user.id, explanation).run();
  return json({ id: result.meta.last_row_id }, 201);
}

async function deleteConnection(request, env, id) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const conn = await env.DB.prepare('SELECT id, user_id FROM song_connections WHERE id = ?1').bind(id).first();
  if (!conn) return json({ error: 'Connexion introuvable.' }, 404);
  if (conn.user_id !== user.id && !user.is_admin) return json({ error: 'Vous ne pouvez supprimer que vos propres connexions.' }, 403);

  await env.DB.batch([
    env.DB.prepare('DELETE FROM song_connections WHERE id = ?1').bind(id),
  ]);
  return json({ ok: true });
}

/* -------------------------------------------- interprétations d'ensemble */

// Valide les connexions entre blocs d'une interprétation d'ensemble.
// Retourne un tableau normalisé, ou une Response d'erreur.
async function parseEssayLinks(env, raw) {
  if (raw == null) return [];
  if (!Array.isArray(raw)) return json({ error: 'Connexions invalides.' }, 400);
  if (raw.length > 20) return json({ error: '20 connexions maximum par interprétation.' }, 400);
  const links = [];
  for (const l of raw) {
    const note = String((l && l.note) || '').trim();
    if (!note) return json({ error: 'Chaque connexion doit être expliquée.' }, 400);
    if (note.length > 1000) return json({ error: 'Explication de connexion trop longue (1000 caractères max).' }, 400);
    const spec = { note };
    for (const side of ['from', 'to']) {
      const lineId = Number(l && l[side + '_line_id']);
      const line = await env.DB.prepare('SELECT id, text FROM lyric_lines WHERE id = ?1').bind(lineId).first();
      if (!line) return json({ error: 'Phrase introuvable dans une connexion.' }, 400);
      let ws = l[side + '_word_start'] == null ? null : Number(l[side + '_word_start']);
      let we = l[side + '_word_end'] == null ? ws : Number(l[side + '_word_end']);
      if (ws != null) {
        const n = countWords(line.text);
        if (!Number.isInteger(ws) || !Number.isInteger(we) || ws < 0 || we < ws || we >= n) {
          return json({ error: 'Position de mot invalide dans une connexion.' }, 400);
        }
      } else {
        we = null;
      }
      spec[side] = { line_id: lineId, ws, we };
    }
    if (spec.from.line_id === spec.to.line_id &&
        spec.from.ws === spec.to.ws && spec.from.we === spec.to.we) {
      return json({ error: 'Une connexion doit relier deux blocs différents.' }, 400);
    }
    links.push(spec);
  }
  return links;
}

async function replaceEssayLinks(env, essayId, links) {
  const statements = [
    env.DB.prepare('DELETE FROM essay_links WHERE essay_id = ?1').bind(essayId),
  ];
  links.forEach((l, i) => {
    statements.push(env.DB.prepare(
      `INSERT INTO essay_links
        (essay_id, position, from_line_id, from_word_start, from_word_end,
         to_line_id, to_word_start, to_word_end, note)
       VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)`
    ).bind(essayId, i, l.from.line_id, l.from.ws, l.from.we, l.to.line_id, l.to.ws, l.to.we, l.note));
  });
  await env.DB.batch(statements);
}

async function createEssay(request, env) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const body = await readJson(request);
  if (!body) return json({ error: 'Requête invalide.' }, 400);
  const songId = Number(body.song_id);
  const content = String(body.content || '').trim();
  if (!content) return json({ error: 'L’interprétation ne peut pas être vide.' }, 400);
  if (content.length > 10000) return json({ error: 'Interprétation trop longue (10 000 caractères max).' }, 400);

  const song = await env.DB.prepare('SELECT id FROM songs WHERE id = ?1').bind(songId).first();
  if (!song) return json({ error: 'Chanson introuvable.' }, 404);

  const links = await parseEssayLinks(env, body.links);
  if (links instanceof Response) return links;

  const result = await env.DB.prepare(
    'INSERT INTO essays (song_id, user_id, content, is_published, version_id) VALUES (?1, ?2, ?3, 0, NULL)'
  ).bind(songId, user.id, content).run();
  const essayId = result.meta.last_row_id;
  if (links.length) await replaceEssayLinks(env, essayId, links);
  return json({ id: essayId }, 201);
}

async function updateEssay(request, env, id) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const essay = await env.DB.prepare('SELECT id, user_id FROM essays WHERE id = ?1').bind(id).first();
  if (!essay) return json({ error: 'Interprétation introuvable.' }, 404);
  if (essay.user_id !== user.id && !user.is_admin) {
    return json({ error: 'Vous ne pouvez modifier que vos propres interprétations.' }, 403);
  }

  const body = await readJson(request);
  const content = String((body && body.content) || '').trim();
  if (!content) return json({ error: 'L’interprétation ne peut pas être vide.' }, 400);
  if (content.length > 10000) return json({ error: 'Interprétation trop longue (10 000 caractères max).' }, 400);

  const links = await parseEssayLinks(env, body.links);
  if (links instanceof Response) return links;

  await env.DB.prepare(
    `UPDATE essays SET content = ?1, updated_at = datetime('now'), is_published = 0, version_id = NULL WHERE id = ?2`
  ).bind(content, id).run();
  if (body.links !== undefined) await replaceEssayLinks(env, id, links);
  return json({ ok: true });
}

async function deleteEssay(request, env, id) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const essay = await env.DB.prepare('SELECT id, user_id FROM essays WHERE id = ?1').bind(id).first();
  if (!essay) return json({ error: 'Interprétation introuvable.' }, 404);
  if (essay.user_id !== user.id && !user.is_admin) {
    return json({ error: 'Vous ne pouvez supprimer que vos propres interprétations.' }, 403);
  }
  await env.DB.batch([
    env.DB.prepare('DELETE FROM essays WHERE id = ?1').bind(id),
  ]);
  return json({ ok: true });
}

/* ------------------------------------------------------------------ compte */

async function updateUsername(request, env) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const body = await readJson(request);
  const username = String((body && body.username) || '').trim();
  if (!/^[\p{L}\p{N} _.-]{3,30}$/u.test(username)) {
    return json({ error: 'Le pseudo doit faire entre 3 et 30 caractères (lettres, chiffres, espaces, . _ -).' }, 400);
  }
  if (username === user.username) return json({ ok: true, username });

  const existing = await env.DB.prepare(
    'SELECT id FROM users WHERE username = ?1 COLLATE NOCASE AND id <> ?2'
  ).bind(username, user.id).first();
  if (existing) return json({ error: 'Ce pseudo est déjà pris.' }, 409);

  const result=await env.DB.prepare('UPDATE users SET username = ?1 WHERE id = ?2 AND NOT EXISTS(SELECT 1 FROM users WHERE username=?1 COLLATE NOCASE AND id<>?2)').bind(username, user.id).run();
  if(!result.meta.changes)return json({error:'Ce pseudo est déjà pris.'},409);
  return json({ ok: true, username });
}

async function updatePassword(request, env) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const body = await readJson(request);
  const stop=await barrage(request,env,'password:'+user.id,10,900);if(stop)return stop;
  const current = String((body && body.current_password) || '');
  const next = String((body && body.new_password) || '');
  if(current.length>1024||next.length>1024)return json({error:'Mot de passe trop long.'},400);
  if (next.length < 8) return json({ error: 'Le nouveau mot de passe doit faire au moins 8 caractères.' }, 400);

  const row = await env.DB.prepare('SELECT password_hash FROM users WHERE id = ?1').bind(user.id).first();
  if (!row || !(await verifyPassword(current, row.password_hash))) {
    return json({ error: 'Mot de passe actuel incorrect.' }, 401);
  }

  const hash = await hashPassword(next);
  const updated=await env.DB.prepare('UPDATE users SET password_hash = ?1 WHERE id = ?2 AND password_hash = ?3').bind(hash,user.id,row.password_hash).run();
  if(!updated.meta.changes)return json({error:'Le mot de passe a déjà été modifié. Reconnecte-toi avant de réessayer.'},409);

  // Changer de mot de passe coupe toutes les autres sessions : si un cookie a
  // fuité, il ne vaut plus rien après ce geste. On garde seulement la session
  // en cours, pour ne pas se déconnecter soi-même.
  const token = getCookie(request, SESSION_COOKIE);
  await env.DB.prepare('DELETE FROM sessions WHERE user_id = ?1 AND token <> ?2')
    .bind(user.id, token || '').run();
  return json({ ok: true });
}

// La photo est recadrée en carré et compressée côté client avant l'envoi :
// on ne stocke jamais un fichier brut potentiellement lourd.
async function updateAvatar(request, env) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }

  const body = await readJson(request);
  const dataUrl = String((body && body.data) || '');
  const m = dataUrl.match(/^data:(image\/(?:jpeg|png|webp));base64,([a-zA-Z0-9+/=]+)$/);
  if (!m) return json({ error: 'Image invalide.' }, 400);
  const [, mime, base64] = m;
  if (base64.length > 350_000) return json({ error: 'Image trop lourde.' }, 400);
  let bytes;
  try{bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));}catch{return json({error:'Image invalide.'},400);}
  const signature=(offset,values)=>values.every((value,i)=>bytes[offset+i]===value);
  const valid=bytes.length>=12&&(mime==='image/jpeg'?signature(0,[255,216,255]):mime==='image/png'?signature(0,[137,80,78,71,13,10,26,10]):signature(0,[82,73,70,70])&&signature(8,[87,69,66,80]));
  if(!valid)return json({error:'Image invalide.'},400);

  await env.DB.prepare(
    'UPDATE users SET avatar_data = ?1, avatar_mime = ?2 WHERE id = ?3'
  ).bind(base64, mime, user.id).run();
  return json({ ok: true });
}

/* -------------------------------------- historique de progression et droits privés */

// Toute la logique du jeu est dans src/enigmas57.js et ne quitte jamais le
// Worker : le client ne reçoit une réponse qu'une fois trouvée.

// La table de progression est additive et n'existe que pour cette page : on
// la crée à la volée si la migration 0009 n'a pas encore été appliquée, une
// seule fois par isolat. `migrations/0009_signes57.sql` reste la référence.
let riddleTableReady = false;
async function ensureRiddleTable(env) {
  if (riddleTableReady) return;
  await env.DB.batch([
    env.DB.prepare(
      `CREATE TABLE IF NOT EXISTS riddle_progress (
         user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
         riddle_id TEXT NOT NULL,
         hints_used INTEGER NOT NULL DEFAULT 0,
         revealed INTEGER NOT NULL DEFAULT 0,
         solved_at TEXT,
         updated_at TEXT NOT NULL DEFAULT (datetime('now')),
         PRIMARY KEY (user_id, riddle_id)
       )`
    ),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_riddle_progress_user ON riddle_progress(user_id)'),
  ]);
  riddleTableReady = true;
}

// Une ligne par réponse trouvée.
async function riddleRows(env, userId) {
  await ensureRiddleTable(env);
  const { results } = await env.DB.prepare(
    'SELECT riddle_id, solved_at FROM riddle_progress WHERE user_id = ?1'
  ).bind(userId).all();
  // Un nœud a pu être réuni à un autre depuis : la progression suit.
  return (results || []).map((r) => ({ ...r, riddle_id: currentAnswerId(r.riddle_id) }));
}

/* ---------------------------------- références autonomes sur un passage ---
   Sur un passage, trois choses indépendantes peuvent être dites : une
   interprétation, une référence à un passage d'un autre morceau, ou une
   référence à une œuvre. Les deux dernières vivent ici, avec la même cible
   qu'une annotation, et sans dépendre d'une interprétation.               */

// Créée à la volée si la migration 0011 n'a pas encore été appliquée.
let passageRefTableReady = false;
async function ensurePassageRefTable(env) {
  if (passageRefTableReady) return;
  await env.DB.batch([
    env.DB.prepare(
      `CREATE TABLE IF NOT EXISTS passage_references (
         id INTEGER PRIMARY KEY AUTOINCREMENT,
         user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
         song_id INTEGER NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
         target_type TEXT NOT NULL DEFAULT 'passage',
         line_id INTEGER REFERENCES lyric_lines(id) ON DELETE CASCADE,
         word_start INTEGER,
         word_end INTEGER,
         end_line_id INTEGER REFERENCES lyric_lines(id) ON DELETE CASCADE,
         kind TEXT NOT NULL,
         label TEXT NOT NULL,
         artist TEXT,
         note TEXT,
         ref_song_id INTEGER REFERENCES songs(id) ON DELETE CASCADE,
         ref_line_id INTEGER REFERENCES lyric_lines(id) ON DELETE CASCADE,
         ref_end_line_id INTEGER REFERENCES lyric_lines(id) ON DELETE CASCADE,
         created_at TEXT NOT NULL DEFAULT (datetime('now'))
       )`
    ),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_passage_refs_song ON passage_references(song_id)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_passage_refs_target ON passage_references(ref_song_id)'),
  ]);
  passageRefTableReady = true;
}

async function createPassageReference(request, env) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }
  const body = await readJson(request);
  if (!body) return json({ error: 'Requête invalide.' }, 400);

  const songId = Number(body.song_id);
  const song = await env.DB.prepare('SELECT id FROM songs WHERE id = ?1').bind(songId).first();
  if (!song) return json({ error: 'Chanson introuvable.' }, 404);

  // La cible est décrite comme celle d'une annotation.
  const targetType = ['song', 'title', 'line', 'word', 'passage'].includes(body.target_type)
    ? body.target_type : 'passage';
  const lineId = body.line_id == null ? null : Number(body.line_id);
  const endLineId = body.end_line_id == null ? null : Number(body.end_line_id);
  const wordStart = body.word_start == null ? null : Number(body.word_start);
  const wordEnd = body.word_end == null ? null : Number(body.word_end);

  const parsed = await parseReferences(env, [body]);
  if (parsed instanceof Response) return parsed;
  if (!parsed.length) return json({ error: 'Référence vide.' }, 400);
  const r = parsed[0];
  if (!r.note) return json({ error: 'Expliquez en quoi c’est une référence.' }, 400);

  await ensurePassageRefTable(env);
  await env.DB.prepare(
    `INSERT INTO passage_references
      (user_id, song_id, target_type, line_id, word_start, word_end, end_line_id,
       kind, label, artist, note, ref_song_id, ref_line_id, ref_end_line_id)
     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)`
  ).bind(
    user.id, songId, targetType, lineId, wordStart, wordEnd, endLineId,
    r.ref_line_id ? 'internal' : 'work', r.label, r.artist, r.note,
    r.ref_song_id || null, r.ref_line_id || null, r.ref_end_line_id || null
  ).run();
  return json({ ok: true });
}

async function deletePassageReference(request, env, id) {
  let user;
  try { user = await requireUser(request, env); } catch (resp) { return resp; }
  await ensurePassageRefTable(env);
  const row = await env.DB.prepare('SELECT id, user_id FROM passage_references WHERE id = ?1').bind(id).first();
  if (!row) return json({ error: 'Référence introuvable.' }, 404);
  if (row.user_id !== user.id && !user.is_admin) return json({ error: 'Action non autorisée.' }, 403);
  await env.DB.prepare('DELETE FROM passage_references WHERE id = ?1').bind(id).run();
  return json({ ok: true });
}

/* ---------------------------------------------------------------- admin */

async function adminCreateAlbum(request, env) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  const body = await readJson(request);
  const title = String((body && body.title) || '').trim();
  if (!title) return json({ error: 'Le titre est requis.' }, 400);
  const releaseDate = String((body && body.release_date) || '').trim() || null;
  const isSingle = body && body.is_single ? 1 : 0;
  const slug = await uniqueSlug(env, 'albums', slugify(title));
  const maxPos = await env.DB.prepare('SELECT COALESCE(MAX(position), 0) AS p FROM albums').first();
  const result = await env.DB.prepare(
    'INSERT INTO albums (title, slug, release_date, is_single, position) VALUES (?1, ?2, ?3, ?4, ?5)'
  ).bind(title, slug, releaseDate, isSingle, maxPos.p + 1).run();
  return json({ id: result.meta.last_row_id, slug }, 201);
}

async function adminUpdateAlbum(request, env, id) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  const body = await readJson(request);
  const album = await env.DB.prepare('SELECT id FROM albums WHERE id = ?1').bind(id).first();
  if (!album) return json({ error: 'Album introuvable.' }, 404);
  const title = String((body && body.title) || '').trim();
  if (!title) return json({ error: 'Le titre est requis.' }, 400);
  const releaseDate = String((body && body.release_date) || '').trim() || null;
  const isSingle = body && body.is_single ? 1 : 0;
  await env.DB.prepare(
    'UPDATE albums SET title = ?1, release_date = ?2, is_single = ?3 WHERE id = ?4'
  ).bind(title, releaseDate, isSingle, id).run();
  return json({ ok: true });
}

async function adminDeleteAlbum(request, env, id) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  await env.DB.prepare('DELETE FROM albums WHERE id = ?1').bind(id).run();
  return json({ ok: true });
}

async function adminCreateSong(request, env) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  const body = await readJson(request);
  const title = String((body && body.title) || '').trim();
  if (!title) return json({ error: 'Le titre est requis.' }, 400);
  const albumId = body && body.album_id ? Number(body.album_id) : null;
  const trackNumber = body && body.track_number ? Number(body.track_number) : null;
  const youtubeUrl = String((body && body.youtube_url) || '').trim() || null;
  if (albumId != null) {
    const album = await env.DB.prepare('SELECT id FROM albums WHERE id = ?1').bind(albumId).first();
    if (!album) return json({ error: 'Album introuvable.' }, 404);
  }
  const slug = await uniqueSlug(env, 'songs', slugify(title));
  const result = await env.DB.prepare(
    'INSERT INTO songs (album_id, title, slug, track_number, youtube_url) VALUES (?1, ?2, ?3, ?4, ?5)'
  ).bind(albumId, title, slug, trackNumber, youtubeUrl).run();
  return json({ id: result.meta.last_row_id, slug }, 201);
}

async function adminUpdateSong(request, env, id) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  const body = await readJson(request);
  const song = await env.DB.prepare('SELECT id FROM songs WHERE id = ?1').bind(id).first();
  if (!song) return json({ error: 'Chanson introuvable.' }, 404);
  const title = String((body && body.title) || '').trim();
  if (!title) return json({ error: 'Le titre est requis.' }, 400);
  const albumId = body && body.album_id ? Number(body.album_id) : null;
  const trackNumber = body && body.track_number ? Number(body.track_number) : null;
  const youtubeUrl = String((body && body.youtube_url) || '').trim() || null;
  await env.DB.prepare(
    'UPDATE songs SET title = ?1, album_id = ?2, track_number = ?3, youtube_url = ?4 WHERE id = ?5'
  ).bind(title, albumId, trackNumber, youtubeUrl, id).run();
  return json({ ok: true });
}

async function adminDeleteSong(request, env, id) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  await env.DB.prepare('DELETE FROM songs WHERE id = ?1').bind(id).run();
  return json({ ok: true });
}

// Durée de la chanson, au format "m:ss" ou en secondes.
async function adminSetDuration(request, env, id) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  const body = await readJson(request);
  const song = await env.DB.prepare('SELECT id FROM songs WHERE id = ?1').bind(id).first();
  if (!song) return json({ error: 'Chanson introuvable.' }, 404);

  const raw = String((body && body.duration) || '').trim();
  let seconds = null;
  if (raw !== '') {
    const m = raw.match(/^(\d+):([0-5]?\d)$/);
    if (m) seconds = Number(m[1]) * 60 + Number(m[2]);
    else if (/^\d+$/.test(raw)) seconds = Number(raw);
    else return json({ error: 'Format de durée invalide (utilisez m:ss, par exemple 3:57).' }, 400);
  }
  await env.DB.prepare('UPDATE songs SET duration_seconds = ?1 WHERE id = ?2').bind(seconds, id).run();
  return json({ ok: true, duration_seconds: seconds });
}

// Remplace l'intégralité du texte d'une chanson. Attention : les
// annotations liées aux anciennes lignes sont supprimées (cascade).
async function adminSetLyrics(request, env, id) {
  try { await requireAdmin(request, env); } catch (resp) { return resp; }
  const body = await readJson(request);
  const song = await env.DB.prepare('SELECT id FROM songs WHERE id = ?1').bind(id).first();
  if (!song) return json({ error: 'Chanson introuvable.' }, 404);

  const text = String((body && body.text) || '').replace(/\r\n/g, '\n');
  const lines = text.split('\n').map((l) => l.trim());
  while (lines.length && lines[lines.length - 1] === '') lines.pop();
  while (lines.length && lines[0] === '') lines.shift();

  const statements = [
    env.DB.prepare('DELETE FROM lyric_lines WHERE song_id = ?1').bind(id),
  ];
  lines.forEach((line, i) => {
    statements.push(
      env.DB.prepare('INSERT INTO lyric_lines (song_id, line_number, text) VALUES (?1, ?2, ?3)').bind(id, i + 1, line)
    );
  });
  await env.DB.batch(statements);
  return json({ ok: true, line_count: lines.filter((l) => l !== '').length });
}
