// Editorial chapters stay on the server: future revelations are never shipped
// in the public JavaScript. Videos may be added to a chapter as {title,url}.
import {gameLevel,buildGameState} from './echelon.js';
import {buildOpenings} from './content-access.js';

export const CHAPTERS = [
  {level:1,title:'Bienvenue en enfer',text:'Vulpis était en enfer. Les quatre morceaux de 57 racontent sa recherche d’un chemin vers le paradis. Pour entrer dans cette histoire, écoute les morceaux, lis leurs paroles et cherche les signes qu’il y a laissés. Ton premier objectif semble simple : comprendre comment il s’en est échappé. Un mot, un son ou un rapprochement peut changer ta lecture. Propose tes découvertes dans Échelons : chaque réponse complète distincte te fait avancer.'},
  {level:2,title:'Une histoire, plusieurs lectures',text:'Un même passage peut porter plusieurs sens. Dans 57, les nombres côtoient des images, les expressions se répondent et les sonorités déplacent les mots. Ne cherche pas seulement une phrase secrète : observe ce qui change quand tu écoutes autrement. Tu peux désormais échanger dans Conversation, en partageant tes pistes sans priver les autres du plaisir de chercher.'},
  {level:3,title:'Le mouvement entre les morceaux',text:'13h20 annonce un passage ; Orange semble raconter l’autre côté. Entre les deux, 30 vins divins et Sans indices dans les dés multiplient les rapprochements. Écoute l’album comme un trajet : quels mots reviennent, quelles images se transforment et qu’est-ce qui paraît avoir changé à l’arrivée ? Garde plusieurs hypothèses ouvertes.'},
  {level:4,title:'Donner une forme à ce qui déborde',text:'Le papier, la musique et les mélanges reviennent dans le récit de Vulpis. Ce qui se déroule à l’intérieur commence à prendre une forme que quelqu’un d’autre peut regarder ou entendre. L’enfer et le paradis restent les lieux de cette histoire, mais prête aussi attention aux gestes : écrire, rapprocher, transformer, partager.'},
  {level:5,title:'Un détour par le 18 juillet 2019',text:'Avant Vulpis, dont le récit se situe au début de 2023, il y a 18 juillet 2019. Wanheda ouvre cette remontée dans le temps. On y rencontre des pensées qui débordent, des mots devenus personnages et la difficulté de rester présent. Écoute ce morceau comme une trace antérieure : certaines images de 57 ont déjà une histoire, et leur sens se précise lorsqu’on revient en arrière.'},
  {level:6,title:'Derrière Vulpis',apocalypse:true,text:'Première apocalypse, au sens de révélation : Vulpis est un personnage créé par White Cadae, dans le contexte de son vécu avec un trouble schizoaffectif. Ce que tu prenais pour une fuite hors de l’enfer change de sens. Le véritable objectif de cet escape game est de découvrir White Cadae, de comprendre comment il vit ce trouble et comment il cherche, à travers la création et l’introspection, à mieux se comprendre et à devenir une meilleure version de lui-même. Quand je vois je pense, écrit bien avant Vulpis, permet de reprendre cette histoire depuis la façon dont il décrit ses images mentales.'},
  {level:7,title:'Relier les deux infinis',text:'Un fil entre deux infinis poursuit le retour à 2019. White Cadae y décrit des émotions qui prennent forme, des pensées qui se mêlent et une recherche de stabilité. Les images du très grand et du très petit donnent un langage à cette expérience intérieure. Rapproche-les des morceaux de Vulpis : ce sont des façons de raconter son vécu, pas une carte littérale de l’univers.'},
  {level:8,title:'Relire Vulpis après la révélation',text:'Reviens maintenant à 57, au début de 2023. Les anges, l’enfer et le paradis peuvent se relire à la lumière des textes de 2019 et du personnage de Vulpis. Demande-toi ce que chaque image permet d’exprimer. Le récit n’a pas disparu : tu disposes simplement d’un contexte nouveau pour entendre ce que sa première lecture laissait de côté.'},
  {level:9,title:'Extérioriser pour regarder autrement',text:'Dans Wanheda, une idée cherche à sortir ; dans Orange, elle trouve notamment le papier. Cette circulation entre ce qui est vécu et ce qui est exprimé traverse le parcours. La Vidéographie s’ouvre à ce palier : elle offre un espace pour mettre une pensée en forme et la revisiter. Les vidéos de White Cadae viendront, au fil de leur ajout, apporter son propre éclairage sur cette démarche.'},
  {level:10,title:'Ce qui nous met en mouvement',text:'Avec La matière danse, l’attention se déplace vers les causes, les conséquences et les chemins propres à chacun. Le texte invite à regarder ce qui précède une pensée ou une envie de changer. Dans la continuité de 2019 et de Vulpis, une nouvelle question apparaît : qu’est-ce qui façonne la manière dont White Cadae se regarde et cherche à évoluer ?'},
  {level:11,title:'Observer celui qui observe',text:'Quand je vois je pense décrit un souvenir reconstruit dans le présent. La matière danse interroge, à son tour, ce qui conditionne nos pensées. Mets ces deux propositions côte à côte : regarder son passé ne consiste pas seulement à le retrouver, mais aussi à le relire depuis ce que l’on est devenu. Ici, tu explores la façon dont les textes racontent ce mouvement.'},
  {level:12,title:'Les filtres et les possibles',text:'Les probabilités ajoute la question des filtres : ce que l’on remarque influence les directions que l’on envisage. Le morceau emploie un vocabulaire d’observation et de possibilités pour parler de cette expérience. Prends-le comme une proposition poétique de White Cadae : comment sa manière de voir agit-elle sur ce qu’il souhaite essayer, exprimer ou changer ?'},
  {level:13,title:'Comparer plutôt que conclure trop vite',text:'Une image peut traverser plusieurs morceaux sans y jouer exactement le même rôle. Choisis-en une et suis ses transformations entre 2019, 57 et les titres que tu viens de découvrir. Ce rapprochement ne demande pas de tout faire entrer dans une seule explication : il aide à distinguer ce qui se répète, ce qui évolue et ce qui reste encore ouvert.'},
  {level:14,title:'Faire mieux à sa manière',text:'Fais Mieux formule directement une intention déjà présente dans les autres morceaux : se regarder, comprendre ce qui nous façonne et chercher à faire mieux à sa manière. Le parcours te ramène ainsi à l’objectif révélé à l’échelon 6. Comprendre White Cadae, c’est aussi écouter ce qu’il cherche à améliorer, sans réduire sa personne à son trouble ni sa démarche à une promesse de perfection.'},
  {level:15,title:'Rassembler ce que tu as entendu',text:'Tu peux désormais rapprocher trois moments : les textes de 2019, le récit de Vulpis au début de 2023 et l’invitation de Fais Mieux. Quelles images ont changé de sens pour toi ? Lesquelles restent difficiles à comprendre ? Conserve ces questions : les explications et les vidéos à venir pourront enrichir cette lecture, sans que tu aies besoin de combler les blancs à leur place.'},
  {level:16,title:'Révélation à définir',apocalypse:true,pending:true,text:'La deuxième apocalypse, au sens de révélation, sera définie ici. Son contenu reste à définir par White Cadae.'},
  {level:17,title:'Une pensée sur les pensées',text:'Meta moi propose une nouvelle mise en perspective : la pensée qui examine les mécanismes fait elle-même partie de ces mécanismes. Relie cette proposition à Quand je vois je pense. White Cadae revient sur l’acte de s’observer, avec une autre formulation. L’intérêt de ce rapprochement est d’entendre les nuances entre les textes, plutôt que d’en déduire une réponse unique.'},
  {level:18,title:'Le passé dans le présent',text:'Dans Meta moi, le passé participe à la forme des pensées suivantes. Le détour par 2019 prend alors une place particulière : il donne de la profondeur au personnage apparu en 2023. Tu connais maintenant plusieurs traces écrites à rapprocher ; elles permettent de lire une évolution, sans supposer que les paroles racontent chaque événement de la vie de leur auteur.'},
  {level:19,title:'Les personnages comme langage',text:'Reviens aux personnages et aux présences que les textes mettent en scène. Depuis la révélation sur Vulpis, tu sais qu’un personnage peut être une manière de raconter quelque chose de soi. Observe ce que la mise en scène rend sensible : un conflit, une relation, un mouvement ou une aspiration. Les explications personnelles de White Cadae pourront préciser ce que les textes seuls laissent indécis.'},
  {level:20,title:'Ne pas effacer les tensions',text:'Les morceaux font coexister l’envie de fuir et celle d’habiter le monde, le débordement et la recherche de stabilité. Écouter ces tensions aide à ne pas aplatir le récit en une réussite simple et définitive. Le parcours se construit aussi avec ce qui résiste : comprendre une image n’efface pas la difficulté qu’elle cherche à exprimer.'},
  {level:21,title:'Une œuvre à remettre en contexte',text:'Tu n’entends plus Orange de la même façon qu’à ton arrivée. C’est le contexte qui a changé : les paroles sont les mêmes, mais d’autres morceaux et la révélation sur Vulpis accompagnent désormais ton écoute. Essaie de distinguer ce que le texte dit, ce que White Cadae a expliqué et ce que tu proposes toi-même comme interprétation.'},
  {level:22,title:'Faire dialoguer les lectures',text:'Une autre personne peut remarquer un détail qui t’avait échappé. Dans Conversation, les indices, les interprétations et les idées ont chacun leur place. Présente tes rapprochements comme des pistes et appuie-les sur les morceaux accessibles à tes interlocuteurs. Le dialogue peut enrichir la compréhension sans transformer une lecture personnelle en vérité imposée.'},
  {level:23,title:'Du dedans vers une forme partageable',text:'Entre les mots-personnages de Wanheda, le papier d’Orange et les mécanismes de Meta moi, une question revient : comment rendre une expérience intérieure perceptible à quelqu’un d’autre ? Les chansons en proposent plusieurs formes. Les vidéos viendront ajouter une voix et un contexte à cette découverte, lorsqu’elles auront été choisies et publiées par White Cadae.'},
  {level:24,title:'Distinguer comprendre et tout expliquer',text:'Les signes trouvés ouvrent des lectures ; ils ne donnent pas à eux seuls une explication complète d’une personne. À ce stade, tu peux relier davantage d’éléments tout en laissant des questions en suspens. Cette place laissée à l’inconnu fait aussi partie de la découverte de White Cadae : son récit pourra continuer à se préciser avec ses propres mots.'},
  {level:25,title:'Revenir au point de départ',text:'Relis le premier paragraphe puis réécoute Orange. La sortie de l’enfer était la porte d’entrée du récit ; tu sais maintenant que le parcours invite à découvrir White Cadae et son effort pour mieux se comprendre. Note ce qui a évolué dans ton écoute depuis le début. La prochaine révélation reste à écrire : inutile d’en deviner le contenu à la place de son auteur.'},
  {level:26,title:'Révélation à définir',apocalypse:true,pending:true,text:'La troisième apocalypse, au sens de révélation, sera définie ici. Son contenu reste à définir par White Cadae.'},
];

export function buildStory(rows=[],user=null){
  const score=gameLevel(rows),level=Math.max(1,score),author=!!user?.is_admin;
  const openings=buildOpenings(rows,user||{});
  const chapters=CHAPTERS.filter(c=>author||c.level<=level).map(c=>({...c,videos:c.videos||[],access:openings.items.filter(i=>i.open&&Math.max(1,i.level)===c.level&&!['home','profile'].includes(i.id))}));
  const clock=buildGameState(rows).pages.find(n=>n.kind==='clock');
  return {score,level,author,chapters,nextLevel:CHAPTERS.find(c=>c.level>level)?.level||null,
    nextAccess:openings.items.filter(i=>!i.open),
    historicalAccess:openings.items.filter(i=>i.exception==='historical'&&i.level>level),
    discovery:clock?{title:'Horloge',href:clock.href}:null};
}
